build_from:
  amd64: ghcr.io/mcarbonneaux/caddy-proxy-manager-ha:amd64-1.4-ha.1
  aarch64: ghcr.io/mcarbonneaux/caddy-proxy-manager-ha:aarch64-1.4-ha.1
  armv7: ghcr.io/mcarbonneaux/caddy-proxy-manager-ha:armv7-1.4-ha.1
  armhf: ghcr.io/mcarbonneaux/caddy-proxy-manager-ha:armhf-1.4-ha.1
  i386: ghcr.io/mcarbonneaux/caddy-proxy-manager-ha:i386-1.4-ha.1

squash: false
