[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:init-config]
command=/usr/local/bin/init-config.sh
autostart=true
autorestart=false
startsecs=0
exitcodes=0
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:caddy]
command=/usr/bin/caddy run --config /data/config/caddy.json
depends_on=init-config
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
envFiles=/data/config/addon.env

[program:cpm]
command=node /app/server.js
depends_on=init-config
autostart=true
autorestart=true
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
envFiles=/data/config/addon.env
